### ISSUE TITLE
Naming convention for different time subsets

### ISSUE THREAD

**Issue by amirzia** [digitraceslab/niimpy#102]
Features for each data type can computed over different time subsets. For example, `number of calls` can be computed over the whole duration of study, weekends, weekdays, mornings, etc. We should come up with a universal naming convention for the subsets.

Example:
- Time of day: `morning` (6-12), `afternoon` (12-18), `evening` (18-24), `night` (0-6), `all`
- Type of day: `weekend`, `weekday` (working days), `all`

**Comment by ArgonSilicon** [comment]
The naming conventions should be study specific, not universal.
