### ISSUE TITLE
Plotly not rendering in sphinx

### ISSUE THREAD

**Issue by rkdarst** [digitraceslab/niimpy#145]
I found this that implied the problem was related to sphinx_rtd_theme:
https://github.com/readthedocs/sphinx_rtd_theme/issues/788
or maybe this in Sphinx: https://github.com/sphinx-doc/sphinx/issues/9563

The first one says it is fixed, but we use the latest version but it still doesn't work.  I'll keep investigating and use this to track.

One thing I'll try is using a different theme.

**Comment by ArgonSilicon** [comment]
It looks like that changing the plotly renderer to "png" will make the plots visible on readthedocs pages.

fig.show(renderer="png") for single plot. There should be way to set the default for whole notebook.

**Comment by rkdarst** [comment]
That would work!

If you want plotly (which I think would be nice, see this: https://myst-nb.readthedocs.io/en/latest/render/interactive.html#plotly - it is actually still interactive), I got it working with sphinx-book-theme (and maybe one other thing, I forget now.  It might have been downgrading mathjax, see the first warning that is here: https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax  .  Or maybe it was using myst-parser...
I'll figure out tomorrow.

How much would you value plotly showing up?

Overall, sphinx_rtd_theme is starting to show its age and hasn't been updated as often as I would like.  It's not too bad yet, but it wouldn't be too bad to find a replacement.

**Comment by rkdarst** [comment]
It seems a user could independently install most of this using a miniconda or virtual environment.

**Comment by rkdarst** [comment]
OK, this is what makes interactive plotly plots work:, 
- `myst_nb` instead of `nbsphinx`
- Add to conf.py:
  ```
  # needed for plotly, see https://myst-nb.readthedocs.io/en/latest/render/interactive.html#plotly
  html_js_files = ["https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"]
  ```

... and it works with sphinx_rtd_theme.
