### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by rantahar** [digitraceslab/niimpy#17]
We should check that tests cover the important use cases. At least they should cover the steps in the tutorial, user stories and standard workflows.

Creating a test coverage report is straightforward with the `coverage` tool (https://coverage.readthedocs.io/en/coverage-5.5/). It can be installed with 
```
pip install coverage
```

Then you can create an HTML report with
```
coverage run -m pytest
coverage html
```

Should we add this process to the repository somehow? I don't think this needs to be automatic. If we ever add a really detailed contributions guide, maybe this should be mentioned there.

---
Codecov:
https://docs.codecov.com/docs

**Comment by rantahar** [comment]
Html files are in `htmlcov/index.html`

**Comment by rantahar** [comment]
Or using Codecov on GitHub

**Comment by lnknguyen** [comment]
Probably resolved in #100. Should we move this card to Done @rantahar @ArgonSilicon ?
