### ISSUE TITLE
Specify data format and column names

### ISSUE THREAD

**Issue by amirzia** [digitraceslab/niimpy#181]
Since in the feature extraction codes, we take dataframes as input and it is assumed that the columns follow a particular naming format, it would be necessary to document this naming schema.

Currently, there are at least two pages in the documentation that try to address this issue ([https://niimpy.readthedocs.io/en/latest/schema/](https://niimpy.readthedocs.io/en/latest/schema/) and
[https://niimpy.readthedocs.io/en/latest/aware/](https://niimpy.readthedocs.io/en/latest/aware/)). However, they are not complete. They need to be revised and probably merged.

**Comment by ArgonSilicon** [comment]
solved
