### ISSUE TITLE
Required packages for documentation examples

### ISSUE THREAD

**Issue by rantahar** [digitraceslab/niimpy#242]
It would be useful to have a list of packages required to run each example in the documentation in the beginning of the page.

Maybe a console cell with "pip install config package2 ..."

**Comment by rantahar** [comment]
Or perhaps all the packages are installed the "config" module is not actually the PyPi package named "config" :)

The PyPi package does not contain config.MULTIUSER_AWARE_BATTERY_PATH, so this would need to be set up somehow. In any case, this step seems to be missing.

**Comment by ArgonSilicon** [comment]
Moved config under niimpy folder
