### ISSUE TITLE
location data bins but does not bin

### ISSUE THREAD

**Issue by AnaTomomi** [digitraceslab/niimpy#256]
Location preprocessing bins the data for the clean up, but not for the actual preprocessing. Suppose we have a dataframe with GPS data for 7 days and we want to know the daily distance. If the whole dataframe is fed to the function, then the function computes the distance over the whole 7 days. There is no chance of resampling. This resampling needs to be done outside, it means, we need to slice the dataframe in days and then use the function to compute the daily distance.

**Comment by rantahar** [comment]
I believe this was addressed when standardizing location.py
