### ISSUE TITLE
Group by device

### ISSUE THREAD

**Issue by AnaTomomi** [digitraceslab/niimpy#257]
Is there an use case where one user has several devices (e.g., one person two phones) and do we want to make the case for it in the code?

**Comment by rkdarst** [comment]
I had assumed there was, and that's why there is a `device` column in all of the databases (in addition to `user`).  I'm not sure if this has been used much.

**Comment by rantahar** [comment]
Several preprocessing functions group only by user, not by device. In practice this might not happen that often, but it would not be complicated to fix.
