### ISSUE TITLE
The function get_subjects() is not working properly

### ISSUE THREAD

**Issue by arc1909** [digitraceslab/niimpy#27]
In preprocess.py, the function “get_subjects()” uses the ‘AwareHyksConverter’ table to get a list of users. The table is not present in any of the current databases.

**Comment by rkdarst** [comment]
This table is from a different study, so the function is not general enough.  Needs to be fixed.  I guess we can work on it after rearranging everything.

Likely a `preprocess.get_subjects` function isn't needed, something such as `data['user'].unique()` would probably be the better way to get this list, and if you need a list beyond one dataframe it needs to be specified by the user.
