### ISSUE TITLE
reading read_sqlite function missing character encoding

### ISSUE THREAD

**Issue by ArgonSilicon** [digitraceslab/niimpy#283]
- read_sqlite function does not decode Finnish characters correctly

Something like this does the trick (for Finnish characters):

def decode_chars(series):
    decoded = [row.encode('iso-8859-1').decode('utf-8') for row in series.values]
    return decoded

**Comment by rantahar** [comment]
The database itself should contain the encoding information and it seems that the sqlite3 library we use should use that encoding information. So I think the encoding in the database itself is incorrect.

This does happen often, though. The encoding can be set incorrectly in a files metadata. I could add a utility to re-encode and decode data when this happens.

This could be done with the string accessor:
```python
for col in df.columns:
    if df[col].dtype == object:  # if column is of text type
        df[col] = df[col].str.encode('iso-8859-1').str.decode('utf-8')
```

**Comment by rantahar** [comment]
It's preprocessing.utils.set_encoding()
