### ISSUE TITLE
Pandas dependency

### ISSUE THREAD

**Issue by AlirezaT99** [digitraceslab/niimpy#338]
Hi!

In numerous parts of the code, the attribute `include_groups=False` has been set while calling the [*pandas.DataFrame.apply*](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.apply.html). function. The attribute was previously unavailable in pandas "<2.0.0". However this dependency is not enforced in Niimpy; therefore, running scripts in environments with older versions runs into errors.

### Niimpy Version
1.2.0

### Current Behaviour
Installing Niimpy does not consider versions for dependencies, leading to some errors like mentioned.

### Expected Behaviour
Dependency versions should be specified (e.g., in `pyproject.toml`) to be enforced at package installation.

**Comment by rantahar** [comment]
Thank you for submitting an issue!

I think this is worth updating directly in the main branch and pushing a minor version to PyPI. I'm fixing this now.

**Comment by rantahar** [comment]
include_groups=False was added to silence warnings in Pandas 2.2 and later. It include_groups=True will become deprecated behavior in a later version.

**Comment by rantahar** [comment]
A lot of tests fail with pandas 2.0

**Comment by rantahar** [comment]
I was unable to compile pandas 2.1 on my laptop, so I'm testing with a workflow.

**Comment by rantahar** [comment]
It seems pandas 2.1 is not compatible with numpy < 2.0. Updating to only pandas 2.2.

**Comment by rantahar** [comment]
Version 1.2.1 with the dependency change is in PyPI. Closing this issue.
