### ISSUE TITLE
Names for time intervals: {begin,start} vs {end,stop}

### ISSUE THREAD

**Issue by rkdarst** [digitraceslab/niimpy#64]
For time interval arguments, there is some mixture of {begin, start} and {end, stop}.  It would be good to make this consistent.

So... which is best?  Somehow I think that begin + end is best, but I am not sure what the best principle is.  Thoughts?

**Comment by rantahar** [comment]
None of these are reserved names or especially common in other libraries. Numpy and Pandas use start/stop in documentation (at least for pandas.date_range and numpy.arange). So I suggest using these.
