### ISSUE TITLE
Remove dependence on sqlite

### ISSUE THREAD

**Issue by rantahar** [digitraceslab/niimpy#9]
Migrate the Data1 code to fully use pandas.
 * In __init__(), immediately read the database into a list of pandas dataframes
 * Change the functions that run an sql query to pandas methods

**Comment by rkdarst** [comment]
We now have two functions (with standard interface) to read both csv files and database straight to dataframes: https://niimpy.readthedocs.io/en/latest/input-formats/
The database interface isn't going away yet, but won't be as documented or recommended.  It could be useful for very large data, though.
